---
title: "TidyTuesday, startrek with workflowsets"
  ## content also in  "Hitchhiker's Guide to Responsible machine learning"
subtitle: "Followiung Julia Silge's analysis"
author: "Nicholas Spyrison"
date: "06 Mar 2022"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

# Gist

I am using this as an intro to __tidymodels__ and __workflowsets__. I am following along with Julia Silge's analysis and video post. See https://juliasilge.com/blog/star-trek/ for the blog and video.


# Setup

```{r}
if(F)
  install.packages(c("tidyverse", "tidymodels", "tidytext", "tidylo"))

library(tidyverse)
computer_raw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-17/computer.csv")

naniar::vis_miss(computer_raw)

computer_raw %>%
  distinct(value_id, .keep_all = TRUE) %>%
  count(char_type)
```


Which words are more likely to be spoken by a computer vs. by a person?

```{r}
library(tidytext)
library(tidylo)

computer_counts <-
  computer_raw %>%
  distinct(value_id, .keep_all = TRUE) %>%
  unnest_tokens(word, interaction) %>%
  count(char_type, word, sort = TRUE)

computer_counts %>%
  bind_log_odds(char_type, word, n) %>%
  filter(n > 10) %>%
  group_by(char_type) %>%
  slice_max(log_odds_weighted, n = 10) %>%
  ungroup() %>%
  ggplot(aes(log_odds_weighted,
    fct_reorder(word, log_odds_weighted),
    fill = char_type
  )) +
  geom_col(alpha = 0.8, show.legend = FALSE) +
  facet_wrap(vars(char_type), scales = "free_y") +
  labs(y = NULL)
```