---
title: "Untitled"
author: "Nick Spyrison"
date: "2/20/2022"
output:
  pdf_document: default
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, cache.lazy = FALSE)
library(dplyr)
library(kableExtra)
library(tidyverse)
```

## LATEX TABLE TESTING



```{r cars, echo=FALSE}
glossary_df <- data.frame(
  Term = knitr:::escape_latex(c(
    "$\\beta_0$", "$\\beta_1$", "$P(T > |t|)", "basis"#, #"biplot", 
           # "projection", "tour", "geodesic interpolation",
           # "intrinsic data dimensionality", "nonlinear model", 
           # "explanatory variables", "response variable",
           # "local explanation"
  )),
  # Notation = knitr:::escape_latex(c(
  #   "$n$", "\\\\$p\\\\$", "$X_{n \\times p}$", "$A_{p \\times d}$"#,
  #   # "", "\\$Y\\_{n \\times d} = X\\_{n \\times p} \\cdot A\\_{p \\times d}$", 
  #   # "", "", "\\$iid\\$", "", "", "", ""
  #   )),
  Alias = knitr:::escape_latex(c(
    "instance, item, case, row (of data)", "feature, column (of data)",
    "", ""#,# "", "embedding", "", "", "", "", 
    #"dependant/input variable, predictors, covariates", 
    #"predicted/dependant/target/output variable", ""
    )),
 Description = knitr:::escape_latex(c(
    "A unit being measured across the variables.",
    "A measure taken across all observations.",
    "$n$ observations of $p$ variables, a complete quantitative matrix.",
    "Of linear projections, an othorgonal component mapping of $p$ down to $d$ dimensions."#,
 #"Visual representation of the basis, showing the direction and magnitude the variable contribute inscribed in a unit circle.",
 # "The resulting space the data multiplied by the basis.",
 # "A dynamic linear projection animated over small changes to the projection basis.",
 # "Creating intermediate basis frames along the shortest path of possible bases.",
 # "The minimal dimensionality data can be represented by.",
 # "A model with numerous, polynomial, or interacting terms that can be difficult to interpret.",
 # "The variables used to predict the response variable.",
 # "The varaible to be precidicted with the explanatory variables.",
 # "Approximation of the linear variable importance of a model in the vicinity of one observation."
  ))
)

vimeo_link_df <- data.frame(
  Reference = c(
    "Figure \\@ref(fig:ch1fig3)", "Figure \\@ref(fig:ch2fig4)", 
    "Figure \\@ref(fig:casepenguins)", "Figure \\@ref(fig:casechocolates)", 
    "Figure \\@ref(fig:casechocolatesinverse)", "Figure \\@ref(fig:casefifa)", 
    "Figure \\@ref(fig:caseames)"),
  Description = c(
    "radial tour, penguins", "grand tour, penguins", "cheem,  penguins", 
    "cheem,  chocolates", "cheem,  chocolates (inverse)", "cheem, fifa", 
    "cheem, ames housing 2018"),
  Link = c("[vimeo.com/676723431](https://vimeo.com/676723431)",
           "[vimeo.com/676723441](https://vimeo.com/676723441)",
           "[vimeo.com/666431172](https://vimeo.com/666431172)",
           "[vimeo.com/666431143](https://vimeo.com/666431143)",
           "[vimeo.com/666431148](https://vimeo.com/666431148)",
           "[vimeo.com/666431163](https://vimeo.com/666431163)",
           "[vimeo.com/666431134](https://vimeo.com/666431134)")
)

supp_mats_df <- data.frame(
  Description = c(
    "spinifex vignette, Getting started with spinifex", 
    "spinifex vignette, Ggproto api", 
    "cheem vignette, Getting started with cheem", 
    "thesis repository", "thesis, pdf format", "thesis, html format"),
  Link = c(
    "[nspyrison.github.io/spinifex/articles/getting-started-with-spinifex.html](https://nspyrison.github.io/spinifex/articles/getting-started-with-spinifex.html)",
    "[nspyrison.github.io/spinifex/articles/ggproto-api.html](https://nspyrison.github.io/spinifex/articles/ggproto-api.html)",
    "[nspyrison.github.io/cheem/articles/getting-started-with-cheem.html](https://nspyrison.github.io/cheem/articles/getting-started-with-cheem.html)",
    "[github.com/nspyrison/thesis_ns](https://github.com/nspyrison/thesis_ns)",
    "[github.com/nspyrison/thesis_ns/blob/master/docs/thesis_ns.pdf](https://github.com/nspyrison/thesis_ns/blob/master/docs/thesis_ns.pdf)",
    "[https://nspyrison.github.io/thesis_ns/](https://nspyrison.github.io/thesis_ns/)")
)

## Set format and fonts for pdf vs html:
# if(knitr::is_html_output()){
#   fmt <- "html"
#   fnt <- 12L
#   esc <- FALSE ## HTML likes FALSE in vimeolinks
# }else{
  fmt <- "latex"
  fnt <- 10L
  esc <- FALSE #FALSE ## latex needs \ escaping on urls to use false.
  #TRUE$Link <- gsub("_", "\\_", supp_mats_df$Link) 
# }
```


## Glossary

This thesis was written with statistics terminology. This glossary helps to bridge the language used here to be more accessible to machine learning audiences.

```{r glossary, fig.cap = "Use the caption arg in kable(), not this.", eval=TRUE ,  echo=FALSE , tidy=TRUE, message=FALSE , warning=FALSE , results='asis'}
# glossary_df$Alias <- gsub("$", "\\$", glossary_df$Alias) 
# glossary_df$Description <- gsub("$", "\\$", glossary_df$Description) 
# glossary_df %>%# mutate_all( stringr::str_replace_all, pattern=fixed("$"), replacement="\\$") %>% 
# kableExtra::kbl(
#     format = "latex",
#     booktabs = TRUE, longtable = TRUE, 
#     linesep = "", escape = FALSE,
#     caption = "Glossary of terms") %>%
#  kableExtra::kable_classic(font_size = fnt)

 knitr::kable(glossary_df, format="latex", longtable=T, booktabs = T, linesep = "", row.names = TRUE, escape = FALSE) %>%
  kableExtra::kable_classic()
```


## Animated tour links

```{r vimeolinks, fig.cap = "Use the caption arg in kable(), not this."}
# kableExtra::kbl(
#     vimeo_link_df, format = fmt, align = rep("l", 3),
#     booktabs = TRUE, longtable = TRUE, linesep = "", escape = esc,
#     caption = "Animated tour links") %>%
#   kableExtra::kable_classic(font_size = fnt)
```


## Supplementary material

```{r suppmats, fig.cap = "Use the caption arg in kable(), not this."}
# kableExtra::kbl(
#     supp_mats_df, format = fmt, align = rep("l", 3),
#     booktabs = TRUE, longtable = TRUE, linesep = "", escape = esc,
#     caption = "Supplementary material") %>%
#   kableExtra::kable_classic(font_size = fnt)
```