## qsimulatR
#install.packages("qsimulatR")
library("qsimulatR")
help(package="qsimulatR")
#vignette(package="qsimulatR")
vignette("qsimulatR", "qsimulatR")

## A quantum state
x <- qstate(nbits=2)
x
typeof(x)
class(x)

## Default to |0> state, basis cna be specified
CatInBox <- qstate(nbits=1, basis=c("|dead>", "|alive>"))
CatInBox

## Can give coefficiants -- magnitude to the basis?
CatInBox <- qstate(nbits=1, basis=c("|dead>", "|alive>"),
                   coefs=as.complex(c(1/sqrt(2), 1/sqrt(2))))
CatInBox


## Ploting. uninteresting before gate
plot(x, qubitnames=c("bit1", "bit2"))
plot(CatInBox, qubitnames=c("cat1"))


## single q gate:
x <- qstate(nbits=2)
y <- H(1) * x
y
plot(y, qubitnames=c("bit1", "bit2"))


## New gate function
myGate <- function(bit) {
  methods::new("sqgate", bit=as.integer(bit),
               M=array(as.complex(c(1,0,0,-1)), dim=c(2,2)),
               type="myGate")
}

z <- myGate(1) * y
z

## Truth table; of a logical gate. (not quantum state)
truth.table(X, 1)
truth.table(CNOT, 2)

z <- CNOT(c(1,2)) * y
z
plot(z)


CX12 <- cqgate(bits=c(1L, 2L), gate=X(2L))
z <- CX12 * y
z


z <- SWAP(c(1,2)) * y
z
plot(z)


x <- H(1) *(H(2) * qstate(3))
x

## CCNOT, not an even number of energized states.
y <- CCNOT(c(1,2,3)) * x
y
plot(y)

y <- CSWAP(c(1,2,3)) * x
plot(y)


## Multi-gate circuits as functions
myswap <- function(bits){
  function(x){
    CNOT(bits) * (CNOT(rev(bits)) * (CNOT(bits) * x))
  }
}
truth.table(myswap, 2)

circuit <- myswap(1:2)
plot(circuit(qstate(2)))


## Measurements
res <- measure(y, bit=1, repetitions = 1)
summary(res)
plot(res$psi)


rv <- measure(y, 3, rep=1000)$value
hist(rv, freq=FALSE, main="Probability for Qubit 3")


##Export ot Qiskit
#IBM provides quantum computing platforms, which can be freely used. 
#However, one needs to programme in python using the qiskit package. 
#For convenience, qsimulatR can export a circuit translated to qiskit

if(F){
  filename <- paste0(tempdir(), "/circuit.py")
  export2qiskit(y, filename=filename)
  #which results in the following file
  cat(readLines(filename), sep = '\n')
}
# automatically generated by qsimulatR
#R> qc = QuantumCircuit(3)
#R> qc.h(1)
#R> qc.h(0)
#R> qc.cswap(0, 1, 2)
#R> which can be used at quantum-computing.ibm.com to run on real quantum hardware. Note that the export functionality only works for standard quantum gates, not for customary defined ones.